# environment.yml

# User's minimal environment for macfp

# conda env create -f environment.yml

name: base

channels:
  - conda-forge  # must come before defaults (for gsl version)
  - defaults

dependencies:
  - python >=3.7,<3.10
  - numpy
  - sys
  - math
  - matplotlib
  - pandas
  - importlib

