# environment.yml

# User's minimal environment for macfp (test)

# conda env create -f environment.yml

name: base

channels:
  - defaults

dependencies:
  - python = 3.9
  - numpy
  - matplotlib
  - pandas

