# This is a basic workflow to help you get started with Actions

name: Fire_Growth_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  # push:
    # branches: [ $default-branch, test_branch ]
  pull_request:
    branches: [ master ]
    paths:
      - .github/**
      - Utilities/**
      - Fire_Growth/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r .github/requirements.txt

      # Generate new plots
      - name: Generate Fire_Growth/NIST_Parallel_Panel/Documentation plots
        run: |
          cd ./Fire_Growth/NIST_Parallel_Panel/Documentation
          python plot_burner_heat_flux_centerline.py
          python plot_burner_heat_flux_contour.py
          python plot_pmma_hrr_qrad.py
          python plot_pmma_flame_spread_heat_flux.py

      # # Push updated images to SCRIPT_FIGURES (CANNOT PERFORM THIS STEP ON PULL REQUEST)
      # - name: Upload images to releases
      #   run: |
      #     gh release upload SCRIPT_FIGURES ./Fire_Growth/NIST_Parallel_Panel/Documentation/Burner_heatflux.png --clobber
      #     gh release upload SCRIPT_FIGURES ./Fire_Growth/NIST_Parallel_Panel/Documentation/Burner_heatflux_colormap.png --clobber
      #     gh release upload SCRIPT_FIGURES ./Fire_Growth/NIST_Parallel_Panel/Documentation/PMMA_HRR_q-rad-only.png --clobber
      #     gh release upload SCRIPT_FIGURES ./Fire_Growth/NIST_Parallel_Panel/Documentation/PMMA_flame_spread_heatflux.png --clobber
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

## IF THE PR PASSES AND THE MAINTAINER MERGES THE PR, THEN RERUN AND UPLOAD IMAGES TO RELEASES

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    # branches: [ $default-branch, test_branch ]
  # pull_request:
    branches: [ master ]
    paths:
      - .github/**
      - Utilities/**
      - Fire_Growth/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r .github/requirements.txt

      # Generate new plots
      - name: Generate Fire_Growth/NIST_Parallel_Panel/Documentation plots
        run: |
          cd ./Fire_Growth/NIST_Parallel_Panel/Documentation
          python plot_burner_heat_flux_centerline.py
          python plot_burner_heat_flux_contour.py
          python plot_pmma_hrr_qrad.py
          python plot_pmma_flame_spread_heat_flux.py

      # Push updated images to SCRIPT_FIGURES
      - name: Upload images to releases
        run: |
          gh release upload SCRIPT_FIGURES ./Fire_Growth/NIST_Parallel_Panel/Documentation/Burner_heatflux.png --clobber
          gh release upload SCRIPT_FIGURES ./Fire_Growth/NIST_Parallel_Panel/Documentation/Burner_heatflux_colormap.png --clobber
          gh release upload SCRIPT_FIGURES ./Fire_Growth/NIST_Parallel_Panel/Documentation/PMMA_HRR_q-rad-only.png --clobber
          gh release upload SCRIPT_FIGURES ./Fire_Growth/NIST_Parallel_Panel/Documentation/PMMA_flame_spread_heatflux.png --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



